# A list of command names which should always be wrapped
always_wrap: []

# What character to use for bulleted lists
bullet_char: '*'

# Format command names consistently as 'lower' or 'upper' case
command_case: lower

# If true, emit the unicode byte-order mark (BOM) at the start of the file
emit_byteorder_mark: false

# enable comment markup parsing and reflow
enable_markup: false

# What character to use as punctuation after numerals in an enumerated list
enum_char: .

# Regular expression to match preformat fences in comments default=
# ``r'^\s*([`~]{3}[`~]*)(.*)$'``
fence_pattern: ^\s*([`~]{3}[`~]*)(.*)$

# If comment markup is enabled, don't reflow the first comment block in each
# listfile. Use this to preserve formatting of your copyright/license
# statements.
first_comment_is_literal: false

# Format keywords consistently as 'lower' or 'upper' case
keyword_case: upper

# What style line endings to use in the output.
line_ending: unix

# How wide to allow formatted cmake files
line_width: 80

# If comment markup is enabled, don't reflow any comment block which matches
# this (regex) pattern. Default is `None` (disabled).
literal_comment_pattern: null

# A dictionary containing any per-command configuration overrides. Currently
# only `command_case` is supported.
per_command: {}

# Regular expression to match rulers in comments default=
# ``r'^\s*[^\w\s]{3}.*[^\w\s]{3}$'``
ruler_pattern: ^\s*[^\w\s]{3}.*[^\w\s]{3}$

# If true, separate flow control names from their parentheses with a space
separate_ctrl_name_with_space: false

# If true, separate function names from parentheses with a space
separate_fn_name_with_space: false

# How many spaces to tab for indent
tab_size: 2

# If the statement spelling length (including space and parenthesis) is larger
# than the tab width by more than this amount, then force reject un-nested
# layouts.
max_prefix_chars: 4

# If a statement is wrapped to more than one line, than dangle the closing
# parenthesis on its own line.
dangle_parens: True

# If the trailing parenthesis must be 'dangled' on its on line, then align it
# to this reference: `prefix`: the start of the statement,  `prefix-indent`:
# the start of the statement, plus one indentation  level, `child`: align to
# the column of the arguments
dangle_align: 'prefix-indent'
