- vendor_id:  0xB090C0
  product_code:  0xB0905030
  address:  [0, 0]
- vendor_id:  0xB090C0
  product_code:  0xB0905030
  address:  [0, 1]
- vendor_id:  0xB090C0
  product_code:  0xB0905030
  address:  [0, 2]
- vendor_id:  0xB090C0
  product_code:  0xB0905030
  address:  [0, 3]
- vendor_id:  0xB090C0
  product_code:  0xB0905030
  address:  [0, 4]
- vendor_id:  0xB090C0
  product_code:  0xB0905030
  address:  [0, 5]
