####################################################################
#
#  This configures the Tormach ZA6 robot to work with MoveIt Studio
#
####################################################################

hardware:
  # Used by some hardware description packages.
  type: "tormach"

  # Whether or not the arm is running in simulation mode.
  simulated: False

  # If the MoveIt Studio Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: False

  # If the MoveIt Studio Agent should launch the robot state publisher.
  #
  # This should be false if you are launching the robot state
  # publisher as part of drivers.  [Optional, default=True]
  launch_robot_state_publisher: False

  # Parameters for the robot description. A URDF and SRDF are both required.
  robot_description:
    urdf:
      package: "za6_description"
      path: "urdf/za6.xacro"
    srdf:
      package: "za6_moveit_config"
      path: "config/za6.srdf"
    # Add any additional parameters required for the xacro file here
    urdf_params:
      - use_mock_hardware: False

# Sets ROS global params for launch
ros_global_params:
  use_sim_time: False #"%>> hardware.simulated"  # Whether or not to use simulated ROS time

# Optional parameters
optional_feature_params:
  use_joystick: False
  use_external_webcam: False
  use_formant_bridge: False

# This Configures moveit params that are in moveit_config.py
# The majority of these files should live in the moveit/ directory.
moveit_params:
  joint_group_name: "manipulator"

  ompl_planning:
    package: "moveit_studio_za6_base_config"
    path: "config/moveit/ompl_planning.yaml"
  kinematics:
    package: "za6_moveit_config"
    path: "config/kinematics.yaml"
  servo:
    package: "moveit_studio_za6_base_config"
    path: "config/moveit/za6_servo.yaml"
  servo_kinematics:
    package: "za6_moveit_config"
    path: "config/kinematics.yaml"
  pilz_cartesian_limits:
    package: "za6_moveit_config"
    path: "config/pilz_cartesian_limits.yaml"
  joint_limits:
    package: "za6_moveit_config"
    path: "config/joint_limits.yaml"
  sensors_3d:
    package: "moveit_studio_za6_base_config"
    path: "config/moveit/sensors_3d.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

# Additional parameters for the Studio User interface
ui_params:
  servo_endpoint_frame_id: "manual_grasp_link"  # Specify the grasp pose

# Configuration for loading objectives. Add additional plugin loaders as needed.
objectives:
  # List of plugins for loading custom behaviors.
  behavior_loader_plugins:
    core:
      # Always load MoveIt Studio core behaviors
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
  # Specify source folder for objectives and the tree_nodes_model.xml
  objective_library_paths:
    core:
      package_name: "moveit_studio_za6_base_config"
      relative_path: "objectives"
  # Specify location of the waypoints file.
  waypoints_file:
    package_name: "moveit_studio_za6_base_config"
    relative_path: "config/waypoints.yaml"

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
