#!/usr/bin/env python3

import sys
import logging
from hal_plumber.hw_device_mgr import ZAHWDeviceMgr, ZASimHWDeviceMgr


if __name__ == "__main__":
    argv = list(sys.argv[1:])  # Knock off executable name
    logging.basicConfig(
        format="%(asctime)s [%(levelname)s]%(name)s: %(message)s",
        level=logging.INFO,
    )
    sim = "--sim" in argv
    if sim:
        mgr = ZASimHWDeviceMgr()
    else:
        mgr = ZAHWDeviceMgr()
    mgr.logger.setLevel("info")
    mgr.logger.info(f"Starting in {'sim' if sim else 'hardware'} mode")
    mgr.init(argv)
    mgr.run()
