moveit:
  # MoveIt move group to use
  move_group: 'manipulator'
  # Name of the joints in the move group
  joint_names:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  # Specify whether the robot is allowed to replan if it detects
  # changes in the environment.
  allow_replanning: false
  # Specify the maximum planning time in seconds
  planning_time: 5.0
  # Specify which reference frame to assume for poses specified
  # without a reference frame.
  pose_reference_frame: 'world'
  # Specify which reference frame to use for tool frames, also used as
  # end effector link
  tool_reference_frame: 'tool0'
  # position tolerance that is used for reaching the goal when moving
  # to a pose
  goal_position_tolerance: 0.000001
  # orientation tolerance that is used for reaching the goal when
  # moving to a pose
  goal_orientation_tolerance: 0.0001
  # joint tolerance (for each joint) that is used for reaching the
  # goal when moving to a joint value target
  goal_joint_tolerance: 0.00001
  # joint tolerance (for each joint) that is used for reaching the
  # goal when moving to a joint value target
  goal_joint_correction_tolerance: 0.000000001
  # the number of times the motion plan is to be computed from scratch
  # before the shortest solution is returned
  num_planning_attempts: 1
  # planner to be used for planning
  planner_id: ''
