---
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    # update_rate used in mock_hardware config only
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    streaming_controller:
      type: position_controllers/JointGroupPositionController

joint_trajectory_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    command_interfaces:
    - position
    - velocity
    state_interfaces:
    - position
    - velocity
      # Adding this causes control_node to throw exception, even
      # though it's defined in the ros2_control URDF
      # - effort
    # Silence warning:
    #
    # [joint_trajectory_controller]: [Deprecated]:
    # "allow_nonzero_velocity_at_trajectory_end" is set to true. The
    # default behavior will change to false. (on_init() at
    # ./src/joint_trajectory_controller.cpp:67)
    allow_nonzero_velocity_at_trajectory_end: false

streaming_controller:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    command_interfaces:
    - position
    state_interfaces:
    - position

joint_state_broadcaster:
  ros__parameters:
    joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
