based_on_package: "moveit_studio_za6_base_config"

hardware:

  # Update robot description for machine tending world.
  robot_description:
    urdf:
      package: "moveit_studio_za6_tending_config"
      path: "description/za6_machine_tending.xacro"
    # Add any additional parameters required for the xacro file here
    urdf_params:
      - use_mock_hardware: ${MOCK_HARDWARE:-false}
      - include_ros2_control:  true
      - gripper:  ${ZA_GRIPPER:-none}

objectives:
  objective_library_paths:
    # You must use a unique key for each package.
    # The moveit_studio_za6_base_config uses "core"
    mock_hardware_objectives:
      package_name: "moveit_studio_za6_tending_config"
      relative_path: "objectives"
  waypoints_file:
    package_name: "moveit_studio_za6_tending_config"
    relative_path: "waypoints/machine_tending_waypoints.yaml"
