based_on_package: "moveit_studio_za6_base_config"

hardware:

  # Update robot description for machine tending world.
  robot_description:
    urdf:
      # urdf_params inherited from base config
      package: "moveit_studio_za6_tending_config"
      path: "description/za6_machine_tending.xacro"
    srdf:
      package: "moveit_studio_za6_tending_config"
      path: "config/za6.${ZA_GRIPPER:-none}.srdf"

objectives:
  objective_library_paths:
    # You must use a unique key for each package.
    # The moveit_studio_za6_base_config uses "core"
    mock_hardware_objectives:
      package_name: "moveit_studio_za6_tending_config"
      relative_path: "objectives"
  waypoints_file:
    package_name: "moveit_studio_za6_tending_config"
    relative_path: "waypoints/machine_tending_waypoints.yaml"
